# Dependencies
markdown:         kramdown
kramdown:
      parse_block_html: true
#markdown:         KramdownPygments
#markdown:         CommonMarkGhPages
highlighter:      rouge

# plugins
#gems: [jekyll-paginate]
plugins:
  - jekyll-commonmark-ghpages
  - jekyll-seo-tag
  - jekyll-paginate

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'topics'
tagline:          'Diana Cai'
description:      'on machine learning, statistics, computer science, and research.'
url:              https://dicai.github.io/
baseurl:          /blog

author:
  name:           'Diana Cai'
  url:            https://twitter.com/dianarycai

paginate:         5


pages_list:
    all: '/blog/allposts'
    archive: '/blog/archive'
    compsci: '/blog/compsci'
    mlstats: '/blog/mlstat'
    other: '/blog/other'
#feed: '/atom.xml'
