# Dependencies
markdown:         kramdown
#markdown:         KramdownPygments
highlighter:      rouge

# plugins
#gems: [jekyll-paginate]
plugins:
    - jekyll-seo-tag
    - jekyll-paginate

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'topics'
tagline:          'Diana Cai'
description:      'on machine learning, statistics, computer science, and research.'
url:              https://dicai.github.io/
baseurl:          /blog

author:
  name:           'Diana Cai'
  url:            https://twitter.com/dianarycai

paginate:         5


pages_list:
    stat-ml: '/blog/statml'
    compsci: '/blog/compsci'
    all: '/blog/allposts'
    archive: '/blog/archive'
    other: '/blog/other'
#feed: '/atom.xml'
