# Dependencies
markdown:         kramdown
#markdown:         KramdownPygments
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'topics of interest'
tagline:          'Diana Cai'
description:      'on machine learning, statistics, computer science, and math.'
url:              http://dicai.github.io/
baseurl:          /blog/

author:
  name:           'Diana Cai'
  url:            https://twitter.com/dicai

paginate:         5


pages_list:
    stat-ml: '/statml'
    compsci: '/compsci'
    archive: 'archive'
    other: '/other'
#feed: '/atom.xml'
